# Generated by Django 3.0 on 2020-01-31 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=20)),
                ('color', models.CharField(choices=[('BLU', '#0066ff'), ('GRA', '#6897bb'), ('GRE', '#70818D'), ('ORA', '#ff8800'), ('PUR', '#aa00ff'), ('RED', '#ff5733'), ('YEL', '#fef65b')], default='GRA', max_length=7)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=30)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Todolist',
                'verbose_name_plural': 'Todolists',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('deadline', models.DateTimeField(blank=True)),
                ('status', models.CharField(choices=[('ARCH', 'Archived'), ('DONE', 'Done'), ('OPEN', 'Open')], default='OPEN', max_length=4)),
                ('tags', models.ManyToManyField(related_name='tasks', related_query_name='task', to='todolist.Tag', verbose_name='Tags')),
                ('to_do', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist.ToDo')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
    ]
