# Generated by Django 2.2.2 on 2019-06-24 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='todolist.BaseModel')),
                ('description', models.TextField()),
                ('due_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived'), ('DONE', 'Done')], default='ACTIVE', max_length=8)),
                ('position', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'task',
                'verbose_name_plural': 'tasks',
            },
            bases=('todolist.basemodel',),
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='todolist.BaseModel')),
                ('position', models.PositiveIntegerField()),
                ('tasks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist.Task')),
            ],
            options={
                'verbose_name': 'list',
                'verbose_name_plural': 'lists',
            },
            bases=('todolist.basemodel',),
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='todolist.BaseModel')),
                ('lists', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist.List')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'board',
                'verbose_name_plural': 'boards',
            },
            bases=('todolist.basemodel',),
        ),
    ]
