# Generated by Django 2.2.2 on 2019-06-24 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='lists',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='todolist.List'),
        ),
        migrations.AlterField(
            model_name='list',
            name='tasks',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='todolist.Task'),
        ),
    ]
