# Generated by Django 2.2.2 on 2019-06-24 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todolist', '0003_auto_20190624_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnList',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='todolist.BaseModel')),
                ('position', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'list',
                'verbose_name_plural': 'lists',
            },
            bases=('todolist.basemodel',),
        ),
        migrations.RemoveField(
            model_name='board',
            name='lists',
        ),
        migrations.RemoveField(
            model_name='board',
            name='users',
        ),
        migrations.AddField(
            model_name='board',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='List',
        ),
        migrations.AddField(
            model_name='columnlist',
            name='user_board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist.Board'),
        ),
        migrations.AddField(
            model_name='task',
            name='column_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todolist.ColumnList'),
        ),
    ]
