# Generated by Django 3.0 on 2020-02-12 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_auto_20200212_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tasks', related_query_name='task', to='todolist.Tag', verbose_name='Tags'),
        ),
    ]
