# Generated by Django 2.2.2 on 2019-06-30 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_auto_20190624_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columnlist',
            name='user_board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='todolist.Board'),
        ),
    ]
