# Generated by Django 3.0 on 2020-03-29 18:47

from django.db import migrations, models
import justdoit.todolist.models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0009_auto_20200328_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(null=True, upload_to=justdoit.todolist.models.profile_picture),
        ),
    ]
